package sandbox

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/mdubb86/devm/internal/config"
	"github.com/mdubb86/devm/internal/schema"
)

// ForwardEnv is the host env vars we propagate into every interactive
// sbx exec so TUIs see correct terminal capabilities. These vary per
// terminal session and cannot live in the shared /.devm/.env file.
var ForwardEnv = []string{"TERM", "COLORTERM", "LANG", "LC_ALL", "LC_CTYPE"}

// EnvArgs returns the `-e KEY=VALUE` args for sbx exec covering
// per-session host-forwarded terminal vars only. Persistent project
// + service env lives in /.devm/.env (see PersistentEnv) and is
// sourced by the with-devm-env wrapper, not propagated as flags.
func EnvArgs(cfg schema.Config) []string {
	var args []string
	for _, k := range ForwardEnv {
		if v := os.Getenv(k); v != "" {
			args = append(args, "-e", fmt.Sprintf("%s=%s", k, v))
		}
	}
	return args
}

// PersistentEnv returns the contents of .devm/.env: a shell-sourceable
// file with `export KEY='value'` lines covering everything persistent
// devm wants in the sandbox's env. Sorted, deterministic, single-quoted.
//
// Contents (sorted by key):
//  1. cfg.Env entries (which by this point includes WORKSPACE and
//     IS_SANDBOX, injected by schema.ResolveEnv).
//  2. Per-service flattened env: NAME_KEY = VALUE.
//  3. Per-service injected ports: NAME_PORT (and NAME_HOST when set)
//     when svc.EnvInject is true and the service name does NOT begin
//     with "supabase" (collides with the supabase CLI's env prefix).
//
// Trailing line, emitted unsorted at the end so $WORKSPACE has been
// exported above it:
//
//	export PATH="$WORKSPACE/.devm/scripts:$PATH"
func PersistentEnv(cfg schema.Config) string {
	merged := make(map[string]string, len(cfg.Env)*2)

	for k, v := range cfg.Env {
		merged[k] = v
	}

	svcNames := make([]string, 0, len(cfg.Services))
	for n := range cfg.Services {
		svcNames = append(svcNames, n)
	}
	sort.Strings(svcNames)
	for _, name := range svcNames {
		svc := cfg.Services[name]
		upper := strings.ToUpper(name)
		isSupabasePrefix := strings.HasPrefix(strings.ToLower(name), "supabase")

		if svc.EnvInject && svc.Port != 0 && !isSupabasePrefix {
			merged[upper+"_PORT"] = fmt.Sprintf("%d", config.BindPort(cfg, svc.Port))
			if svc.EnvHost != "" {
				merged[upper+"_HOST"] = svc.EnvHost
			}
		}
		keys := make([]string, 0, len(svc.Env))
		for k := range svc.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			merged[upper+"_"+k] = svc.Env[k]
		}
	}

	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by devm. Do not edit.\n")
	for _, k := range keys {
		b.WriteString("export ")
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(shellSingleQuote(merged[k]))
		b.WriteByte('\n')
	}
	b.WriteString(`export PATH="$WORKSPACE/.devm/scripts:$PATH"`)
	b.WriteByte('\n')
	return b.String()
}

// shellSingleQuote wraps v in single quotes, escaping any embedded
// single quote via the POSIX 'closing-quote, backslash-quote, opening-quote'
// dance: foo'bar → 'foo'\''bar'.
func shellSingleQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}
