package mutagen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestComposeConfig_DefaultsFirstUserLast(t *testing.T) {
	cfg := ComposeConfig([]string{"scratch/", "!scratch/keep/"})
	// Defaults appear first, user last, in order.
	assert.Equal(t, DefaultIgnores[0], cfg.Ignores[0])
	assert.Equal(t, "scratch/", cfg.Ignores[len(cfg.Ignores)-2])
	assert.Equal(t, "!scratch/keep/", cfg.Ignores[len(cfg.Ignores)-1])
	assert.Equal(t, "two-way-resolved", cfg.SyncMode)
	assert.Equal(t, "accelerated", cfg.ScanMode)
	assert.False(t, cfg.VCSIgnore)
	assert.Equal(t, 1, cfg.Version)
}

func TestWriteConfigFile_AtomicAndReadable(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sub", "myproject", "main.yml")
	cfg := ComposeConfig([]string{"foo/"})
	require.NoError(t, WriteConfigFile(path, cfg))

	body, err := os.ReadFile(path)
	require.NoError(t, err)
	s := string(body)
	assert.Contains(t, s, "mode: two-way-resolved")
	assert.Contains(t, s, "scanMode: accelerated")
	assert.Contains(t, s, "- \"foo/\"")
	assert.Contains(t, s, "- \"**/node_modules/\"")
	assert.True(t, strings.HasPrefix(s, "# generated by devm; do not edit\n"))

	info, err := os.Stat(path)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0644), info.Mode().Perm())
}

func TestConfigFilePath_JoinsCorrectly(t *testing.T) {
	got := ConfigFilePath("/base", "shelfmates", "repo")
	assert.Equal(t, "/base/shelfmates/repo.yml", got)
}
