package mutagen

import (
	"fmt"
	"os"
	"path/filepath"
)

// SessionConfig holds the per-session mutagen sync settings written to a
// generated config yaml file.
type SessionConfig struct {
	SyncMode  string // "two-way-resolved"
	ScanMode  string // "accelerated"
	VCSIgnore bool   // false — let ignore list drive .git handling
	Ignores   []string
}

// ComposeConfig prepends DefaultIgnores to userIgnore, sets fixed sync/scan
// modes, and returns a SessionConfig ready to write.
func ComposeConfig(userIgnore []string) SessionConfig {
	ignores := make([]string, 0, len(DefaultIgnores)+len(userIgnore))
	ignores = append(ignores, DefaultIgnores...)
	ignores = append(ignores, userIgnore...)
	return SessionConfig{
		SyncMode:  "two-way-resolved",
		ScanMode:  "accelerated",
		VCSIgnore: false,
		Ignores:   ignores,
	}
}

// ConfigFilePath returns the on-disk path for a session's config yaml.
func ConfigFilePath(mutagenSessionsDir, projectID, label string) string {
	return filepath.Join(mutagenSessionsDir, projectID, label+".yml")
}

// WriteConfigFile writes cfg to path atomically (temp + rename), creating
// parent dirs as needed. Mode 0644.
func WriteConfigFile(path string, cfg SessionConfig) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("mutagen: mkdir %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, ".mutagen-cfg-*.tmp")
	if err != nil {
		return fmt.Errorf("mutagen: temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	body := renderYAML(cfg)
	if _, err := tmp.WriteString(body); err != nil {
		tmp.Close()
		return fmt.Errorf("mutagen: write: %w", err)
	}
	if err := tmp.Chmod(0644); err != nil {
		tmp.Close()
		return fmt.Errorf("mutagen: chmod: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("mutagen: close: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("mutagen: rename: %w", err)
	}
	return nil
}

func renderYAML(cfg SessionConfig) string {
	// mutagen's --configuration-file schema (mutagen 0.18): the file
	// top-level is `global.Configuration` with a single `sync:` field,
	// whose `defaults:` maps to `synchronization.Configuration` (see
	// mutagen/pkg/synchronization/configuration.go). `mode`, `scanMode`,
	// and `ignore.{vcs,paths}` all live under sync.defaults. Anything at
	// the top level other than `sync:` (or a sibling `forward:`) is
	// rejected outright — no `version:`, no top-level `ignores:`.
	out := "# generated by devm; do not edit\n"
	out += "sync:\n"
	out += "  defaults:\n"
	out += fmt.Sprintf("    mode: %s\n", cfg.SyncMode)
	out += fmt.Sprintf("    scanMode: %s\n", cfg.ScanMode)
	out += "    ignore:\n"
	out += fmt.Sprintf("      vcs: %t\n", cfg.VCSIgnore)
	out += "      paths:\n"
	for _, p := range cfg.Ignores {
		out += fmt.Sprintf("        - %q\n", p)
	}
	return out
}
