# Auto-generated by devm. Do not edit — reinstalled on every devm
# bundle sync.
#
# Login shells (bash -l, ssh non-interactive commands, cron with
# BASH_ENV) rebuild PATH via /etc/profile before user-level rc files
# run, so devm's PATH additions in /etc/environment would be lost.
# This drop-in runs at login-shell init after /etc/profile itself,
# re-sourcing /etc/environment via `set -a` so every assignment is
# auto-exported.
#
# The set -a idiom is safe because the encoder in
# internal/render/etc_environment.go (encodeEtcEnvValue) constrains
# /etc/environment values so that shell `set -a; .` and pam_env give
# identical bytes — pinned by
# internal/render/etc_environment_contract_test.go.
if [ -r /etc/environment ]; then
    set -a
    . /etc/environment
    set +a
fi

# Auto-cd to the workspace directory so SSH interactive sessions (and
# any bash -l invocation) land in the project root, matching what
# with-devm-env already does for devm exec / devm shell. Without it,
# `ssh sewtrue` drops the user in $HOME and tools that treat cwd as the
# project root (supabase start, pnpm install, etc.) misfire. Silent
# no-op if $WORKSPACE isn't set or the path doesn't exist.
if [ -n "$WORKSPACE" ] && [ -d "$WORKSPACE" ]; then
    cd "$WORKSPACE" || true
fi
