# Auto-generated by devm. Do not edit — reinstalled on every devm
# bundle sync.
#
# Login shells (bash -l, ssh non-interactive commands, cron with
# BASH_ENV) rebuild PATH via /etc/profile before user-level rc
# files run, so devm's PATH additions in /opt/devm/.env are
# otherwise lost. This drop-in runs at login-shell init after
# /etc/profile itself, restoring devm's env in every login shell.
[ -f /opt/devm/.env ] && . /opt/devm/.env
