#!/usr/bin/env bash
# install-templates: run every per-template installer in .devm/templates/, in glob order.
# Generated by devm; do not edit.
#
# Each per-template installer already knows whether it needs sudo (embedded
# by the renderer from the `sudo:` field in devm.yaml). The dispatcher just
# runs them; a failed installer bubbles up as a cold-start error.
set -euo pipefail
DIR="$WORKSPACE/.devm/templates"
[ -d "$DIR" ] || exit 0
for f in "$DIR"/*.sh; do
    [ -e "$f" ] || continue   # guards "no matches" when nullglob is off
    bash "$f"
done
