#!/usr/bin/env bash
# install-templates: run every per-template installer in .devm/templates/, in glob order.
# Generated by devm; do not edit.
set -euo pipefail
DIR="$WORKSPACE_DIR/.devm/templates"
[ -d "$DIR" ] || exit 0
for f in "$DIR"/*.sh; do
    [ -e "$f" ] || continue   # guards "no matches" when nullglob is off
    bash "$f"
done
