#!/bin/sh
# Auto-generated by devm. Sources .devm/.env then execs argv.
# Source of truth for persistent project + service env in the sandbox.
# Sourcing a missing file is a no-op; we just exec without devm vars.
dir=$(cd "$(dirname "$0")/.." && pwd)
[ -f "$dir/.env" ] && . "$dir/.env"
exec "$@"
