#!/bin/sh
# Auto-generated by devm. Sources .devm/.env then execs argv.
# Source of truth for persistent project + service env in the sandbox.
# Sourcing a missing file is a no-op; we just exec without devm vars.
# readlink -f resolves any symlinks (e.g. /usr/local/bin/with-devm-env →
# $WORKSPACE/.devm/scripts/with-devm-env) so $dir is always .devm/, not
# the symlink's parent.
self=$(readlink -f "$0" 2>/dev/null || echo "$0")
dir=$(cd "$(dirname "$self")/.." && pwd)
if [ -f "$dir/.env" ]; then
    # Apple Virtualization's virtiofs has a guest-side attr/data cache;
    # a fresh read within ~100ms of a host-side rewrite can see a stale
    # truncated view (symptom: `Syntax error: Unterminated quoted string`
    # inside `. .env`). A brief wait forces the cache to age out. 200ms is
    # small enough to not matter for shell startup, big enough to be
    # robust across observed timings.
    sleep 0.2
    . "$dir/.env"
fi

# Terminfo forwarding: install the host's terminfo entry for $TERM
# when the sandbox's terminfo db doesn't already know it (Ghostty,
# recent Wezterm builds, custom forks — anything not in ncurses-term).
# Blob is base64-encoded `infocmp -x` output, passed via -e from
# devm shell. Skips silently when the blob is absent, the entry is
# already installed, or tic fails — same behavior as before in those
# cases.
if [ -n "$DEVM_TERMINFO_BLOB" ] && [ -n "$TERM" ]; then
    if ! infocmp -x "$TERM" >/dev/null 2>&1; then
        printf '%s' "$DEVM_TERMINFO_BLOB" | base64 -d 2>/dev/null \
            | tic -x -o "$HOME/.terminfo" - >/dev/null 2>&1 || true
    fi
    unset DEVM_TERMINFO_BLOB
fi

exec "$@"
