#!/bin/sh
# Auto-generated by devm. Sources /etc/environment then execs argv.
#
# /etc/environment is devm's single canonical env-delivery file. tart
# exec (which is how devm exec/shell run) is not a PAM session and
# does not read /etc/environment on its own — this wrapper carries
# devm's env into every exec via `set -a; . /etc/environment; set +a`
# (auto-exports every assignment to the env for `exec "$@"` below).
#
# The set -a idiom is safe because the encoder in
# internal/render/etc_environment.go (encodeEtcEnvValue) constrains
# /etc/environment values so that both pam_env AND shell `set -a; .`
# produce identical bytes — pinned by
# internal/render/etc_environment_contract_test.go.
if [ -r /etc/environment ]; then
    set -a
    . /etc/environment
    set +a
fi

# Terminfo forwarding: install the host's terminfo entry for $TERM
# when the sandbox's terminfo db doesn't already know it (Ghostty,
# recent Wezterm builds, custom forks — anything not in ncurses-term).
# Blob is base64-encoded `infocmp -x` output, passed via -e from
# devm shell. Skips silently when the blob is absent, the entry is
# already installed, or tic fails — same behavior as before in those
# cases.
if [ -n "$DEVM_TERMINFO_BLOB" ] && [ -n "$TERM" ]; then
    if ! infocmp -x "$TERM" >/dev/null 2>&1; then
        printf '%s' "$DEVM_TERMINFO_BLOB" | base64 -d 2>/dev/null \
            | tic -x -o "$HOME/.terminfo" - >/dev/null 2>&1 || true
    fi
    unset DEVM_TERMINFO_BLOB
fi

# Auto-cd to the workspace directory so `devm shell`, `devm exec` and
# provisioner install: steps all start in the project root — same
# mental model as `docker run -w`, and where a user editing the repo
# expects to land. Silent no-op if $WORKSPACE isn't set (defensive) or
# the path doesn't exist (mount not ready — shouldn't happen post-
# provision, but don't hard-fail).
if [ -n "$WORKSPACE" ] && [ -d "$WORKSPACE" ]; then
    cd "$WORKSPACE" || true
fi

exec "$@"
