package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mdubb86/devm/internal/schema"
)

// Caddyfile generates the VM-side Caddyfile from the validated config.
// One reverse_proxy block per service that declares a hostname.
func Caddyfile(cfg schema.Config) string {
	var sb strings.Builder
	sb.WriteString("# Generated by devm reconcile. DO NOT EDIT.\n\n")
	sb.WriteString("{\n\tauto_https off\n}\n\n")

	// Sort service names so output is deterministic.
	names := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		if cfg.Services[name].Hostname != "" && cfg.Services[name].Port != 0 {
			names = append(names, name)
		}
	}
	sort.Strings(names)

	for _, name := range names {
		svc := cfg.Services[name]
		sb.WriteString(fmt.Sprintf("http://%s {\n\treverse_proxy localhost:%d\n}\n\n", svc.Hostname, svc.Port))
	}
	return sb.String()
}
