package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mdubb86/devm/internal/schema"
)

// WriteDevmEnv renders cfg into repoRoot/.devm/.env via tmpfile +
// rename so a concurrent source by the with-devm-env wrapper cannot
// observe a half-written file. Creates .devm/ if missing.
//
// Idempotent: a second call with the same cfg produces an identical file.
//
// Called from the render write path AND from apply_live on KindEnv* changes.
func WriteDevmEnv(cfg schema.Config, repoRoot string) error {
	dir := filepath.Join(repoRoot, ".devm")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	final := filepath.Join(dir, ".env")
	content := persistentEnv(cfg)

	tmp, err := os.CreateTemp(dir, ".env.*.tmp")
	if err != nil {
		return fmt.Errorf("create tmpfile in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()
	// On any failure after this point, best-effort remove the tmpfile.
	cleanup := func() { _ = os.Remove(tmpPath) }

	if _, err := tmp.WriteString(content); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("write tmpfile: %w", err)
	}
	// fsync before close/rename. Belt-and-suspenders against buffered
	// writes lingering in the kernel: the tmpfile's bytes must be on
	// disk before rename swaps it into place — otherwise the guest's
	// virtiofs client can serve a partial view for a brief window (the
	// scripts/with-devm-env wrapper also sleeps 0.2s before sourcing
	// .env to be robust to this race).
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		cleanup()
		return fmt.Errorf("sync tmpfile: %w", err)
	}
	if err := tmp.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close tmpfile: %w", err)
	}
	if err := os.Chmod(tmpPath, 0o644); err != nil {
		cleanup()
		return fmt.Errorf("chmod tmpfile: %w", err)
	}
	if err := os.Rename(tmpPath, final); err != nil {
		cleanup()
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, final, err)
	}
	return nil
}

// RenderEnv returns the string body of what WriteDevmEnv would write.
// Used by devmbundle.Build to pack into the tar; no host filesystem
// side-effect.
func RenderEnv(cfg schema.Config) (string, error) {
	return persistentEnv(cfg), nil
}

// persistentEnv returns the contents of .devm/.env: a shell-sourceable
// file with `export KEY='value'` lines covering everything persistent
// devm wants in the sandbox's env. Sorted, deterministic, single-quoted.
//
// Contents (sorted by key):
//  1. cfg.Env entries (which by this point includes WORKSPACE and
//     IS_SANDBOX, injected by schema.ResolveEnv).
//  2. Per-service flattened env: NAME_KEY = VALUE.
//
// Trailing line, emitted unsorted at the end so $WORKSPACE has been
// exported above it. cfg.Path entries (already validated + $WORKSPACE-
// expanded by schema.ResolveEnv) prepend devm's internal scripts dir
// AND the container default $PATH:
//
//	export PATH="<cfg.Path[0]>:<cfg.Path[1]>:...:/opt/devm/scripts:$PATH"
//
// When cfg.Path is empty the line collapses to the original
// "/opt/devm/scripts:$PATH" form.
func persistentEnv(cfg schema.Config) string {
	merged := make(map[string]string, len(cfg.Env)*2)

	for k, v := range cfg.Env {
		merged[k] = v.Render()
	}

	svcNames := make([]string, 0, len(cfg.Services))
	for n := range cfg.Services {
		svcNames = append(svcNames, n)
	}
	sort.Strings(svcNames)
	for _, name := range svcNames {
		svc := cfg.Services[name]
		upper := strings.ToUpper(name)

		keys := make([]string, 0, len(svc.Env))
		for k := range svc.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			merged[upper+"_"+k] = svc.Env[k].Render()
		}
	}

	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by devm. Do not edit.\n")
	for _, k := range keys {
		b.WriteString("export ")
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(shellSingleQuote(merged[k]))
		b.WriteByte('\n')
	}
	b.WriteString(`export PATH="`)
	for _, p := range cfg.Path {
		b.WriteString(p)
		b.WriteByte(':')
	}
	b.WriteString(`/opt/devm/scripts:$PATH"`)
	b.WriteByte('\n')
	return b.String()
}

// shellSingleQuote wraps v in single quotes, escaping any embedded
// single quote via the POSIX 'closing-quote, backslash-quote, opening-quote'
// dance: foo'bar → 'foo'\''bar'.
func shellSingleQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}
