package render

import (
	"sort"
	"strings"

	"github.com/mdubb86/devm/internal/schema"
)

// RenderEnv returns the string body of the .env file the devmbundle
// packs into the guest at /opt/devm/.env (via devmbundle.Build and the
// standard install pipe). No host filesystem side-effect — the bundle
// refactor's cold-start and ApplyLive paths both go through this, not
// a host-side write.
func RenderEnv(cfg schema.Config) (string, error) {
	return persistentEnv(cfg), nil
}

// persistentEnv returns the contents of .devm/.env: a shell-sourceable
// file with `export KEY='value'` lines covering everything persistent
// devm wants in the sandbox's env. Sorted, deterministic, single-quoted.
//
// Contents (sorted by key):
//  1. cfg.Env entries (which by this point includes WORKSPACE and
//     IS_SANDBOX, injected by schema.ResolveEnv).
//  2. Per-service flattened env: NAME_KEY = VALUE.
//
// Trailing line, emitted unsorted at the end so $WORKSPACE has been
// exported above it. cfg.Path entries (already validated + $WORKSPACE-
// expanded by schema.ResolveEnv) prepend devm's internal scripts dir
// AND the container default $PATH:
//
//	export PATH="<cfg.Path[0]>:<cfg.Path[1]>:...:/opt/devm/scripts:$PATH"
//
// When cfg.Path is empty the line collapses to the original
// "/opt/devm/scripts:$PATH" form.
func persistentEnv(cfg schema.Config) string {
	merged := make(map[string]string, len(cfg.Env)*2)

	for k, v := range cfg.Env {
		merged[k] = v.Render()
	}

	svcNames := make([]string, 0, len(cfg.Services))
	for n := range cfg.Services {
		svcNames = append(svcNames, n)
	}
	sort.Strings(svcNames)
	for _, name := range svcNames {
		svc := cfg.Services[name]
		upper := strings.ToUpper(name)

		keys := make([]string, 0, len(svc.Env))
		for k := range svc.Env {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			merged[upper+"_"+k] = svc.Env[k].Render()
		}
	}

	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Auto-generated by devm. Do not edit.\n")
	for _, k := range keys {
		b.WriteString("export ")
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(shellSingleQuote(merged[k]))
		b.WriteByte('\n')
	}
	b.WriteString(`export PATH="`)
	for _, p := range cfg.Path {
		b.WriteString(p)
		b.WriteByte(':')
	}
	b.WriteString(`/opt/devm/scripts:$PATH"`)
	b.WriteByte('\n')
	return b.String()
}

// shellSingleQuote wraps v in single quotes, escaping any embedded
// single quote via the POSIX 'closing-quote, backslash-quote, opening-quote'
// dance: foo'bar → 'foo'\”bar'.
func shellSingleQuote(v string) string {
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'"
}
