package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/mtwaage/devm/internal/schema"
)

// SpecYAML generates the sbx kit spec.yaml from the validated config.
// repoRoot is the project's absolute path; used in volume mount paths.
func SpecYAML(cfg schema.Config, repoRoot string) string {
	image := "docker/sandbox-templates:shell-only"
	if cfg.BaseImage.Docker {
		image = "docker/sandbox-templates:shell-docker"
	}

	var sb strings.Builder
	sb.WriteString("# Generated by devm reconcile. DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("schemaVersion: \"1\"\nkind: agent\nname: %s\n", cfg.Project.ID))
	sb.WriteString(fmt.Sprintf("displayName: %s dev\n", cfg.Project.ID))
	sb.WriteString(fmt.Sprintf("description: devm-managed dev sandbox for %s\n\n", cfg.Project.ID))

	sb.WriteString("agent:\n")
	sb.WriteString(fmt.Sprintf("  image: %s\n", image))
	sb.WriteString("  aiFilename: CLAUDE.md\n")
	sb.WriteString("  persistence: persistent\n\n")

	if len(cfg.Network.AllowedDomains) > 0 {
		sb.WriteString("network:\n  allowedDomains:\n")
		for _, d := range cfg.Network.AllowedDomains {
			sb.WriteString(fmt.Sprintf("    - %s\n", d))
		}
		sb.WriteString("\n")
	}

	// Collect ALL masks across services and sort by service name for deterministic output.
	type mEntry struct {
		Path string
		Size string
	}
	var allMasks []mEntry
	names := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		for _, m := range cfg.Services[name].Masks {
			allMasks = append(allMasks, mEntry{Path: m.Path, Size: m.Size})
		}
	}
	if len(allMasks) > 0 {
		sb.WriteString("volumes:\n")
		for _, m := range allMasks {
			sb.WriteString(fmt.Sprintf("  %q: size=%s\n", repoRoot+"/"+m.Path, m.Size))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("environment:\n  variables:\n    IS_SANDBOX: \"1\"\n\n")

	sb.WriteString("commands:\n")
	sb.WriteString("  install:\n")
	sb.WriteString("    - command: 'bash \"$WORKSPACE_DIR/.devm/scripts/provision.sh\"'\n")
	sb.WriteString("      user: \"1000\"\n")
	sb.WriteString("      description: Provision devm dev toolchain\n\n")
	sb.WriteString("  startup:\n")
	sb.WriteString("    - command: ['bash', '-c', 'exec bash \"$WORKSPACE_DIR/.devm/scripts/init-volumes.sh\"']\n")
	sb.WriteString("      user: \"1000\"\n")
	sb.WriteString("      description: Claim ext4 volume mounts for agent user\n")

	return sb.String()
}
