package render

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/mtwaage/devm/internal/schema"
	"gopkg.in/yaml.v3"
)

// SpecYAML generates the sbx kit spec.yaml from the validated config.
// repoRoot is the project's absolute path; used in volume mount paths.
//
// We marshal a typed struct via yaml.v3 rather than building the YAML
// as a string. That removes an entire class of quoting bugs — any
// scalar that requires quoting (wildcards like *.openai.com, strings
// that look like booleans or numbers, paths with special chars) is
// handled by the encoder, not by hand. Previously the string-builder
// approach silently produced invalid YAML when allowed_domains held a
// leading-`*` wildcard (2026-06-05 dogfood failure).
func SpecYAML(cfg schema.Config, repoRoot string) string {
	image := "docker/sandbox-templates:shell"
	if cfg.BaseImage.Docker {
		image = "docker/sandbox-templates:shell-docker"
	}

	spec := kitSpec{
		SchemaVersion: "1",
		Kind:          "agent",
		Name:          cfg.Project.ID,
		DisplayName:   cfg.Project.ID + " dev",
		Description:   "devm-managed dev sandbox for " + cfg.Project.ID,
		Agent: kitAgent{
			Image:      image,
			AIFilename: "CLAUDE.md",
			// Entrypoint is shell-wrapped `sleep infinity </dev/null`. Two
			// load-bearing pieces:
			//   1. sh -c wrapping: sbx daemon propagates session-end cleanup
			//      to the in-VM process for shell-wrapped entrypoints but
			//      not bare commands. exec replaces sh with sleep so no
			//      extra process lingers.
			//   2. </dev/null redirect: detaches sleep's fd 0 from the pty
			//      sbx run allocates for the anchor. Without it the sleep
			//      keeps an open fd to /dev/pts/0 for the sandbox's
			//      lifetime under the live anchor, making it appear as a
			//      phantom session in devm stop's session listing.
			Entrypoint: kitEntrypoint{
				Run: []string{"sh", "-c", "exec sleep infinity </dev/null"},
			},
		},
		// Kit env.variables stays empty. Persistent project + service
		// env (including the devm-owned WORKSPACE and IS_SANDBOX) lives
		// in .devm/.env, sourced by with-devm-env on every sbx exec.
		// Putting cfg.Env in kit env would make every env edit a
		// teardown — incompatible with BucketLive semantics.
		Environment: kitEnvironment{
			Variables: map[string]string{},
		},
	}

	if len(cfg.Network.AllowedDomains) > 0 {
		spec.Network = &kitNetwork{AllowedDomains: cfg.Network.AllowedDomains}
	}

	// Volumes: all masks across services, sorted by service name then
	// declaration order. Sbx kit format is `path: size=N` where the
	// path is the map key.
	names := sortedServiceNames(cfg.Services)
	for _, name := range names {
		for _, m := range cfg.Services[name].Masks {
			if spec.Volumes == nil {
				spec.Volumes = map[string]string{}
			}
			spec.Volumes[repoRoot+"/"+m.Path] = "size=" + m.Size
		}
	}

	// commands.install:
	//   step 0: cleanup (unwrapped — wipes its own potential markers)
	//   step 1: bootstrap.sh (wrapped — devm-managed)
	//   step 2..N+1: user cfg.Install[0..N-1] (each wrapped)
	//   step N+2: sentinel
	//
	// Per the supervision design (2026-06-07), bootstrap.sh auto-prepend
	// is re-enabled. The install marker scheme makes it safe — the
	// 2026-06-05 race is closed by RunShell's install gate.
	spec.Commands.Install = append(spec.Commands.Install,
		kitInstallCommand{Command: installCleanupCmd},
		kitInstallCommand{Command: bootstrapInstallCmd},
	)
	for i, cmd := range cfg.Install {
		stepN := i + 2 // user step indexing starts at 2 (cleanup=0, bootstrap=1)
		spec.Commands.Install = append(spec.Commands.Install, kitInstallCommand{Command: wrapFGInstall(stepN, cmd)})
	}
	spec.Commands.Install = append(spec.Commands.Install, kitInstallCommand{Command: installSentinelCmd})

	// commands.startup: two built-in steps (init-volumes, install-templates)
	// then per-service startup in service-sorted order.
	spec.Commands.Startup = append(spec.Commands.Startup,
		kitStartupCommand{
			Command:     []string{"bash", "-c", `exec bash "$WORKSPACE_DIR/.devm/scripts/init-volumes.sh"`},
			User:        "1000",
			Description: "Claim ext4 volume mounts for agent user",
		},
		kitStartupCommand{
			Command:     []string{"bash", "-c", `exec bash "$WORKSPACE_DIR/.devm/scripts/install-templates.sh"`},
			User:        "0",
			Description: "Install rendered service templates",
		},
	)
	for _, name := range names {
		for idx, step := range cfg.Services[name].Startup {
			wrapped := step
			wrapped.Command = wrapStartupWithDotenvSource(step.Command)
			spec.Commands.Startup = append(spec.Commands.Startup, buildStartupStep(wrapped, name, idx))
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by devm reconcile. DO NOT EDIT.\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(spec); err != nil {
		// Marshal of a fully-typed struct cannot fail in practice. If it
		// does, surface it via the rendered output rather than panicking;
		// LintRenderedSpec would catch any downstream parse failure
		// anyway.
		return fmt.Sprintf("# render error: %v\n", err)
	}
	_ = enc.Close()
	return buf.String()
}

// kitSpec mirrors the subset of the sbx agent-kit schema that devm uses.
// Field tags drive yaml.v3 marshalling — adding `,flow` forces the
// element to be rendered in flow style (square brackets), which is what
// sbx kits use for short string arrays like command argv.
type kitSpec struct {
	SchemaVersion string            `yaml:"schemaVersion"`
	Kind          string            `yaml:"kind"`
	Name          string            `yaml:"name"`
	DisplayName   string            `yaml:"displayName"`
	Description   string            `yaml:"description"`
	Agent         kitAgent          `yaml:"agent"`
	Network       *kitNetwork       `yaml:"network,omitempty"`
	Volumes       map[string]string `yaml:"volumes,omitempty"`
	Environment   kitEnvironment    `yaml:"environment"`
	Commands      kitCommands       `yaml:"commands"`
}

type kitAgent struct {
	Image      string        `yaml:"image"`
	AIFilename string        `yaml:"aiFilename"`
	Entrypoint kitEntrypoint `yaml:"entrypoint"`
}

type kitEntrypoint struct {
	Run []string `yaml:"run,flow"`
}

type kitNetwork struct {
	AllowedDomains []string `yaml:"allowedDomains"`
}

type kitEnvironment struct {
	Variables map[string]string `yaml:"variables"`
}

type kitCommands struct {
	Install []kitInstallCommand `yaml:"install,omitempty"`
	Startup []kitStartupCommand `yaml:"startup"`
}

type kitInstallCommand struct {
	Command string `yaml:"command"`
}

type kitStartupCommand struct {
	Command     []string `yaml:"command,flow"`
	User        string   `yaml:"user,omitempty"`
	Description string   `yaml:"description,omitempty"`
	Background  bool     `yaml:"background,omitempty"`
}

func sortedServiceNames(services map[string]schema.Service) []string {
	names := make([]string, 0, len(services))
	for name := range services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// buildStartupStep builds the kit startup step for a user-defined
// service startup command. When `background: true` is set in
// devm.yaml, we emit the kit-native `background: true` field directly.
//
// History: pre-sbx-0.31 this was a foreground step wrapped at the
// shell level with `nohup <argv> > <log> 2>&1 &` to dodge a quirk
// where kit-level `background: true` steps were killed ~5s after
// launch (docs/sbx-quirks.md quirk #4). sbx 0.31 fixed that — the
// daemon now stays alive past 15s, pinned by
// e2e/test_sbx_quirk_04_kit_background_true.py.
func buildStartupStep(step schema.StartupCommand, service string, _ int) kitStartupCommand {
	if !step.Background {
		return kitStartupCommand{Command: step.Command}
	}
	return kitStartupCommand{
		Command:     step.Command,
		User:        "1000",
		Description: fmt.Sprintf("%s startup daemon", service),
		Background:  true,
	}
}

// dotenvSourcePrefix is the shell snippet that sources .devm/.env if it
// exists. Idempotent and safe to run early (the [ -f ] guard handles the
// case where the file isn't on disk yet, e.g., the very first install
// step before the workspace mount has been claimed).
//
// $WORKSPACE_DIR is set by sbx in every consumer that runs install:,
// startup:, and any sbx exec — pinned by
// e2e/test_sbx_contract_17_install_workspace_dir_and_mount.py and
// e2e/test_sbx_contract_23_env_workspace_dir_set_by_sbx.py.
const dotenvSourcePrefix = `[ -f "$WORKSPACE_DIR/.devm/.env" ] && . "$WORKSPACE_DIR/.devm/.env"`

// wrapStartupWithDotenvSource wraps a user startup command argv so it
// runs after sourcing .devm/.env. The kit startup: form is an argv
// array, so we use the standard POSIX shell idiom:
//
//	sh -c '<source>; exec "$@"' _ <original argv...>
//
// The "_" is a dummy $0; the original argv becomes $@. exec replaces
// the shell so background: true still tracks the user's process.
func wrapStartupWithDotenvSource(userCmd []string) []string {
	if len(userCmd) == 0 {
		return userCmd
	}
	wrapped := []string{
		"sh", "-c",
		dotenvSourcePrefix + `; exec "$@"`,
		"_",
	}
	return append(wrapped, userCmd...)
}

// installCleanupCmd is install step #0: wipes /tmp/.devm for marker
// freshness, then recreates the dir with mode 777 so wrappers running
// as different users (root for install-templates, 1000 for agent
// steps) can all write per-step subdirs. Unwrapped (it would erase
// its own markers if wrapped).
const installCleanupCmd = `sh -c 'rm -rf /tmp/.devm && mkdir -p /tmp/.devm && chmod 777 /tmp/.devm'`

// installSentinelCmd is the terminal install step: marks the entire
// install phase complete. The install gate in RunShell polls for
// /tmp/.devm/install-all-ok to know install has finished.
const installSentinelCmd = `sh -c 'touch /tmp/.devm/install-all-ok'`

// wrapFGInstall renders a single install: command string as
//
//	bash $WORKSPACE_DIR/.devm/scripts/wrap-fg.sh install <N> -- sh -c '<single-quoted user cmd>'
//
// using the same single-quote escape dance as sandbox.PersistentEnv.
func wrapFGInstall(stepN int, userCmd string) string {
	quoted := "'" + strings.ReplaceAll(userCmd, "'", `'\''`) + "'"
	return fmt.Sprintf(
		`bash $WORKSPACE_DIR/.devm/scripts/wrap-fg.sh install %d -- sh -c %s`,
		stepN, quoted,
	)
}

// bootstrapInstallCmd renders install step #1: bootstrap.sh wrapped
// by wrap-fg.sh.
const bootstrapInstallCmd = `bash $WORKSPACE_DIR/.devm/scripts/wrap-fg.sh install 1 -- bash $WORKSPACE_DIR/.devm/scripts/bootstrap.sh`
